import { Alert, Image, Pressable, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import * as ImagePicker from 'expo-image-picker';
import colors from '../theme/colors';
import { Screen, Card } from '../components/Layout';
import { Button, Input } from '../components/Fields';
import { useApp } from '../context/AppContext';

export default function GalleryScreen(){ const { posts,user,addPost,deletePost,addComment,deleteComment,reportComment }=useApp(); const [caption,setCaption]=useState(''); const [image,setImage]=useState<string|undefined>(); const [comments,setComments]=useState<Record<string,string>>({}); async function pick(){ const res=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.8}); if(!res.canceled) setImage(res.assets[0].uri); } function submit(){ if(!caption&&!image) return Alert.alert('Post vazio','Adicione foto ou legenda.'); addPost(caption,image); setCaption(''); setImage(undefined); } function options(postId:string,commentId:string){ Alert.alert('Comentário',['O que deseja fazer?'].join(''),[{text:'Apagar comentário',onPress:()=>deleteComment(postId,commentId)},{text:'Denunciar: indesejado',onPress:()=>reportComment('Comentário indesejado')},{text:'Denunciar: spam',onPress:()=>reportComment('Spam')},{text:'Denunciar: assédio',onPress:()=>reportComment('Assédio')},{text:'Cancelar',style:'cancel'}]); }
return <Screen title="Galeria da Comunidade"><Card><Input label="Legenda" value={caption} onChangeText={setCaption}/>{image?<Image source={{uri:image}} style={{height:180,borderRadius:18,marginBottom:12}}/>:null}<Button title="Selecionar foto" variant="secondary" onPress={pick}/><Button title="Publicar" onPress={submit}/></Card>{posts.map(p=><Card key={p.id}><Text style={{fontWeight:'900',fontSize:17}}>{p.author}</Text><Text style={{color:colors.muted,marginVertical:8}}>{p.caption}</Text>{p.image?<Image source={{uri:p.image}} style={{height:220,borderRadius:22,marginBottom:10}}/>:<View style={{height:140,borderRadius:22,backgroundColor:colors.softBlue,alignItems:'center',justifyContent:'center',marginBottom:10}}><Text style={{color:colors.primary,fontWeight:'900'}}>Post da comunidade</Text></View>}{p.userId===user?.id?<Button title="Apagar publicação" variant="danger" onPress={()=>deletePost(p.id)}/>:null}<Text style={{fontWeight:'900',marginTop:14}}>Comentários</Text>{p.comments.map(c=><Pressable key={c.id} onLongPress={()=>options(p.id,c.id)} style={{paddingVertical:8,borderBottomWidth:1,borderBottomColor:colors.border}}><Text><Text style={{fontWeight:'900'}}>{c.author}: </Text>{c.text}</Text><Text style={{color:colors.muted,fontSize:11}}>Segure para apagar ou denunciar</Text></Pressable>)}<TextInput placeholder="Comentar..." style={{backgroundColor:colors.background,borderRadius:14,padding:12,marginTop:12}} value={comments[p.id]||''} onChangeText={v=>setComments(prev=>({...prev,[p.id]:v}))}/><Button title="Enviar comentário" onPress={()=>{ if(comments[p.id]){addComment(p.id,comments[p.id]); setComments(prev=>({...prev,[p.id]:''}));}}}/></Card>)}</Screen> }
